Adapt to template-haskell-2.11 changes (Kind filed in constructors)
ghc-8's template-haskell-2.11 added support for
Kind polymorphism. That led to addition of Kind
field in constructor which causes build failures:

  src/DeriveArbitrary.hs:81:17: error:
    • The constructor ‘DataD’ should have 6 arguments, but has been given 5
    • In the pattern: DataD _ _ params constructors _
      In the pattern: TyConI (DataD _ _ params constructors _)

Change introduces CPP macro to get support for
both ghc-7.10 and and ghc-8.

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>