src/Misc.hs: fix build failure agains QuickCheck-2.9
QuckCheck introduced more instances in recent versions.
On version 2.9.1 QuickFuzz fails as:

  [ 92 of 135] Compiling Misc             ( src/Misc.hs, dist/build/QuickFuzz/QuickFuzz-tmp/Misc.dyn_o )

  src/Misc.hs:7:10: error:
    Duplicate instance declarations:
      instance Arbitrary a => Arbitrary (Last a)
        -- Defined at src/Misc.hs:7:10
      instance [safe] Arbitrary a => Arbitrary (Last a)
        -- Defined in ‘Test.QuickCheck.Arbitrary’

Raised minimal QuickCheck version up to 2.9.2 to use
upstream instances and dropped Misc module.

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>