src/DeriveArbitrary.hs: tweak for ghc-8
ghc-8 now exposes 'Types' type which collides
with 'Language.Haskell.TH.Syntax.Type':

```
  [ 16 of 134] Compiling DeriveArbitrary  ( src/DeriveArbitrary.hs, dist/build/QuickFuzz/QuickFuzz-tmp/DeriveArbitrary.dyn_o )

  src/DeriveArbitrary.hs:46:50: error:
    Ambiguous occurrence ‘Type’
    It could refer to either ‘Language.Haskell.TH.Syntax.Type’,
                             imported from ‘Language.Haskell.TH.Syntax’ at src/DeriveArbitrary.hs:28:1-33
                          or ‘GHC.Types.Type’,
                             imported from ‘GHC.Types’ at src/DeriveArbitrary.hs:31:1-16
```

Change uses qualified name from template-haskell package.

Signed-off-by: Sergei Trofimovich <siarheit@google.com>